### ISSUE TITLE
Volume Mount

### ISSUE THREAD

**Issue by matteocrippa** [IBM-Swift/swift-ubuntu-docker#1]
I was wondering if it would be interesting to add VOLUME key within the docker file to allow user to mount a local volume.
It would be interesting eg. to allow a mac user to edit locally his file and use only the docker env to compile and test like a sandbox.

Dunno like it happens in other docks mount a volume like

```
/data/swift
```

**Comment by rolivieri** [comment]
@matteocrippa - You can mount a folder on your host to the docker container without having to make changes to the Docker image. For instance, you could execute:

`docker run -i -t -v /Users/olivieri/files:/root/files ibmcom/kitura-ubuntu:latest /bin/bash`

The above command mounts the /Users/olivieri/files (on the host) to the /root/files folder in the docker container. You can then make changes to files that exist on the host and see those files/changes in the container.
