### ISSUE TITLE
Clean apt after installation

### ISSUE THREAD

**Issue by alblue** [IBM-Swift/swift-ubuntu-docker#24]
The image is larger than strictly necessary since it includes the installers around after installation. Appending an `&& apt-get clean` at the end of line 43 can remove the installers, leaving the resulting image a smaller size.

https://github.com/IBM-Swift/swift-ubuntu-docker/blob/16f7f3d94f6bf6af87baa41525a543c66bdeabe8/Dockerfile#L35-L43

**Comment by rolivieri** [comment]
@alblue Thanks for info; change implemented.
