### ISSUE TITLE
clone_build_kitura.sh doesn't exist where expected in last image

### ISSUE THREAD

**Issue by arielelkin** [IBM-Swift/swift-ubuntu-docker#29]
I'm following the steps here:
http://www.kitura.io/en/starter/deploying.html

According to this line:

> From within the Docker container, execute the clone_build_kitura.sh script to build the Kitura-Starter sample project:

There should be a `clone_build_kitura.sh` file in `/root/` of the container.

```
$ docker image ls
ibmcom/kitura-ubuntu   latest              2ce2120d8fe2        12 days ago         1.24 GB
```

```
$ docker run -ti -p 8090:8090 ibmcom/kitura-ubuntu:latest /bin/bash
# ls root/
Kitura-Starter  swift-3.0.2-RELEASE-ubuntu14.04
```

**Comment by rolivieri** [comment]
@arielelkin Unfortunately, the information in the URL you included above is outdated. To run the kitura-starter app in a docker container, you can just do this:

```
$ docker pull ibmcom/kitura-ubuntu:latest
...
$ docker run -i -t ibmcom/kitura-ubuntu:latest
[2017-03-01T08:39:35.515Z] [INFO] [main.swift:28 Kitura_Starter] Server will be started on 'http://localhost:8080'.
[2017-03-01T08:39:35.519Z] [INFO] [HTTPServer.swift:88 listen(on:)] Listening on port 8080
```
For the latest details on the Kitura-Starter app, check out its README: https://github.com/IBM-Bluemix/Kitura-Starter. For up to date info about docker, IBM Containers, and Kitura-Starter, I recommend these blog posts:

- https://developer.ibm.com/swift/2016/02/22/10-steps-to-running-a-swift-app-in-an-ibm-container/
- https://developer.ibm.com/swift/2016/03/04/running-kitura-in-an-ibm-container/
- https://developer.ibm.com/swift/2017/02/14/new-runtime-docker-image-for-swift-applications/

@kfbishop - Do you know who maintains the documentation in http://www.kitura.io/en/starter/deploying.html? It needs to be updated.

**Comment by ianpartridge** [comment]
I stumbled across this issue.  Looks like we fixed the documentation so I'm closing this issue 🙂
