### ISSUE TITLE
The images are marked as Vulnerable in IBM Cloud Container Registry service

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/swift-ubuntu-docker#43]
A quick

```
bx cr image-list
```

shows images based on `swift-ubuntu-runtime` as `Vulnerable`.

**Comment by rolivieri** [comment]
@gmosx My guess is that you are using an old version of the image. I just uploaded the most recent one to my private registry and its status is OK:

```
$ bx cr images
Listing images...

REPOSITORY                                      NAMESPACE   TAG     DIGEST         CREATED      SIZE     VULNERABILITY STATUS   
registry.ng.bluemix.net/olivieri/swift-ubuntu   olivieri    4.0.2   19155ff28b42   5 days ago   452 MB   OK   

OK
```
I recommend you get the latest version of our image (tagged with `4.0.2`) and give it a try.

**Comment by gmosx** [comment]
Actually, I updated to 4.0.2 and it's still marked as 'Vulnerable'.

**Comment by rolivieri** [comment]
@gmosx That's odd, I cannot reproduce that. What specific image are you using (we have two, runtime and development image)? Did you make any changes to the image? Can you share the output you are getting from `bx cr image-list` as I did above? I'd like to see the digest, image size, age of the image, etc. Thanks.

**Comment by gmosx** [comment]
Hm.. actually I checked again and the new images now show up as 'OK'.
Strange, it must have been some kind of container-registry bug.
