### ISSUE TITLE
Update to Ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by Gerrel** [IBM-Swift/swift-ubuntu-docker#46]
Want to run perfect.org, but for ubuntu 14 I have to patch openssl to 1.0.2 (manually without apt-get) to get things working. It's not necessary when ubuntu 16 base image is used.

**Comment by christiancompton** [comment]
@Gerrel Thank you for reaching out.  Our images are based on the LTS used by IBM Cloud, in this case 14.04.  We do not have plans to support 16.04 at this time.
