### ISSUE TITLE
Please support Swift 4.1

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/swift-ubuntu-docker#50]
https://swift.org/blog/swift-4-1-released/

**Comment by christiancompton** [comment]
@gmosx I will begin working on this now.

**Comment by christiancompton** [comment]
https://github.com/IBM-Swift/swift-ubuntu-docker/pull/51

**Comment by christiancompton** [comment]
The 4.1 Image is now available: https://hub.docker.com/r/ibmcom/swift-ubuntu/tags/
