### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by crspybits** [IBM-Swift/swift-ubuntu-docker#70]
Thanks for supporting Kitura Ubuntu Swift Docker images. I just switched over to using them. It did take me a bit of searching to find them. Is this repo linked to the main Kitura repos? (I didn't see such links).

**Comment by ianpartridge** [comment]
If you generate a Kitura application using the CLI then the Dockerfile will use these images. We keep them updated for new Swift releases. Glad they're useful!
