### ISSUE TITLE
Setup CI using Travis CI.

### ISSUE THREAD

**Issue by rolivieri** [IBM-Swift/swift-ubuntu-docker#8]
Automate build, test, and push of the image to DockerHub.

**Comment by BDHernand** [comment]
do we call the image swift-ubuntu-docker?

**Comment by BDHernand** [comment]
what about the extract-libdispatch-binaries.sh file?  Is that supposed to be run after the docker image is built?

**Comment by rolivieri** [comment]
Don't worry about the `extract-libdispatch-binaries.sh` file for now. I will explain how that is used soon.

**Comment by rolivieri** [comment]
This task is just about building the docker image using the `docker build` command and pushing it to docker hub.

**Comment by rolivieri** [comment]
The name of the image is `swift-ubuntu:latest`.

**Comment by BDHernand** [comment]
This has been pushed to master and the image according to travis has been pushed to docker hub
